services:
  postgresdb:
    image: postgres:16-alpine
    container_name: postgresdb
    restart: 'always'
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE_NAME}
    ports:
      - '${DB_PORT:-5434}:5432'
    volumes:
      - dbData:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network
  
  rediscache:
    container_name: rediscache
    image: redis:8.4.0-alpine
    restart: 'no'
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - redisData:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "--no-auth-warning", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  dbData:
    name: db_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/db_data
  
  redisData:
    name: redis_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/redis_data

networks:
  app-network: