services:
  postgresdb:
    image: postgres:16-alpine
    container_name: postgresdb
    restart: 'always'
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE_NAME}
    ports:
        - "5434:5432"

    volumes:
      - dbData:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10

    networks:
      - postgres-network

volumes:
  dbData:
    name: db_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/db_data

networks:
  postgres-network:
    driver: bridge
    driver_opts:
       com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"